name: Arch Linux PDS current CI

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          sed -i 's/noccache="false"/noccache="true"/' customization.cfg
          sed -i 's/cpusched=""/cpusched="pds"/' customization.cfg
          sed -i 's/anbox=""/anbox="false"/' customization.cfg
          sed -i 's/processor_opt=""/processor_opt="skylake"/' customization.cfg
          sed -i 's/compiler=""/compiler="llvm"/' customization.cfg
          sed -i 's/lto_mode=""/lto_mode="full"/' customization.cfg
          sed -i 's/sched_yield_type=""/sched_yield_type="0"/' customization.cfg
          sed -i 's/tickless=""/tickless="1"/' customization.cfg
          sed -i 's/compileroptlevel="1"/compileroptlevel="2"/' customization.cfg
          sed -i 's/timer_freq=""/timer_freq="1000"/' customization.cfg
          sed -i 's/custom_commandline="intel_pstate=passive"/custom_commandline=""/' customization.cfg
          su user -c "yes ''|PKGDEST=/tmp/linux-tkg makepkg --noconfirm -s"

      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-tkg-build
          path: /tmp/linux-tkg
